### PR TITLE
Add more spectraVariables

### PR DESCRIPTION
**Pull request by RogerGinBer**
Hi there @cpanse @tobiasko! 
Here's my PR for parsing more `spectraVariables `from the `rawrrSpectrum` objects. Related to issue #17.

Basically, I've copied the existing strategy of reading a few spectra at a time: I created a reusable function (`.spectrum_get`) that applies a supplied FUN function during the `lapply` so that one may extract whatever they want from the rawrrSpectrum. In this case, `.get_spectrum_metadata` uses a (expandable) dictionary of known variables and extracts whatever it finds.

Then a post-processing function cleans up the columns (type conversion, whitespace removal, etc.) , calculates "derivative" variables (eg. MS2 isolation mz bounds (lower, target, upper) from the precursorMz + isolationOffset +- isolationWidth), etc.

I created some basic tests for the added variables that are present in `coreSpectraVariables`. 
AFAIK, everything is working as intended, both with the package test data and some IDX data of my own, but I'd like you to also give it a try and see if there's any other variables you want added 👍

### CODE REVIEW

**Comment by cpanse** [comment]
@RogerGinBer 
thanks; can you replace `rawrr::readSpectrum` by  `rawrr:::readTrailer`?! using `rawrr:::readTrailer` you avoid reading the entire spectra of all raw files. 

Example:
```{r}
R> rawrr:::readTrailer(rawfileEH4547)
stdout: /tmp/Rtmpk6JVUX/file31700c7ce7e4
stderr: /tmp/Rtmpk6JVUX/file3170043125893
Read 62 items
 [1] "Multiple Injection:"           "Multi Inject Info:"            "AGC:"                          "Micro Scan Count:"             "Scan Segment:"                
 [6] "Scan Event:"                   "Master Index:"                 "Charge State:"                 "Monoisotopic M/Z:"             "Ion Injection Time (ms):"     
[11] "Max. Ion Time (ms):"           "FT Resolution:"                "MS2 Isolation Width:"          "MS2 Isolation Offset:"         "AGC Target:"                  
[16] "HCD Energy:"                   "Analyzer Temperature:"         "=== Mass Calibration: ===:"    "Conversion Parameter B:"       "Conversion Parameter C:"      
[21] "Temperature Comp. (ppm):"      "RF Comp. (ppm):"               "Space Charge Comp. (ppm):"     "Resolution Comp. (ppm):"       "Number of Lock Masses:"       
[26] "Lock Mass #1 (m/z):"           "Lock Mass #2 (m/z):"           "Lock Mass #3 (m/z):"           "LM Search Window (ppm):"       "LM Search Window (mmu):"      
[31] "Number of LM Found:"           "Last Locking (sec):"           "LM m/z-Correction (ppm):"      "=== Ion Optics Settings: ===:" "S-Lens RF Level:"             
[36] "S-Lens Voltage (V):"           "Skimmer Voltage (V):"          "Inject Flatapole Offset (V):"  "Bent Flatapole DC (V):"        "MP2 and MP3 RF (V):"          
[41] "Gate Lens Voltage (V):"        "C-Trap RF (V):"                "====  Diagnostic Data:  ====:" "Dynamic RT Shift (min):"       "Intens Comp Factor:"          
[46] "Res. Dep. Intens:"             "CTCD NumF:"                    "CTCD Comp:"                    "CTCD ScScr:"                   "RawOvFtT:"                    
[51] "LC FWHM parameter:"            "Rod:"                          "PS Inj. Time (ms):"            "AGC PS Mode:"                  "AGC PS Diag:"                 
[56] "HCD Energy eV:"                "AGC Fill:"                     "Injection t0:"                 "t0 FLP:"                       "Access Id:"                   
[61] "Analog Input 1 (V):"           "Analog Input 2 (V):"          
R> collisionEnergy <- rawrr:::readTrailer(rawfileEH4547, "HCD Energy eV:") 
R> collisionEnergy|>tail()
[1] "33.235" "33.988" "35.324" "30.271" "30.952" "37.759"
```

the current rawrr releases (bioc stable/testing) contain a bug for using that function so please use
http://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr_1.7.3.tar.gz

Also, I will make the ::: function public asap

C

**Comment by RogerGinBer** [comment]
Thanks @cpanse! Your way is much quicker and elegant: I'll refactor using `rawrr::readTrailer` 👍 

I've installed rawrr version 1.7.4 from the link you provided and tried the function with the test data, but I'm always getting "BEGIN DEBUG" as the first element of the vector. Is this the expected output format?

```r 
sample_raw_file <- file.path(system.file(package = "rawrr"),
                                'extdata', 'sample.raw')
rawrr:::readTrailer(x, "AGC:") |> head()   ## >> "BEGIN DEBUG " "On" "On" "On" "On" "On" 
rawrr:::readTrailer(x, "Ion Injection Time (ms):") |> head()  ## Same for any other variable name
```
Also, if possible, could you remove the messages from readTrailer (or show them only when a parameter `verbose = TRUE`)?

Cheers,
Roger

**Comment by cpanse** [comment]
@RogerGinBer 

I forgot that we have that `readTrailer` function. You could almost not find it because it was hidden. Sorry.

the debug will disappear with the latest rawrr.1.7.3.exe. Therefore please run `rawrr::installRawrrExe ()` or `rawrr::buildRawrrExe()`:
```
> rawrr::installRawrrExe ()
trying URL 'https://github.com/fgcz/rawrr/releases/download/1.7.3/rawrr.1.7.3.exe'
Content type 'application/octet-stream' length 28672 bytes (28 KB)
==================================================
downloaded 28 KB

MD5 d618a123df8adecada532ed1fa025176 /Users/cp/Library/Caches/org.R-project.R/R/rawrr/rawrrassembly/rawrr.exe
[1] 0
> rawrr::sampleFilePath() |> rawrr:::readTrailer("AGC:") |> head() 
stdout: /var/folders/km/gsm2l7vx2qlb5h46f0qcrwnc0000gn/T//Rtmpkxk5jU/file9d472cf9d5e0
stderr: /var/folders/km/gsm2l7vx2qlb5h46f0qcrwnc0000gn/T//Rtmpkxk5jU/file9d472dba4c0
Read 573 items
[1] "On" "On" "On" "On" "On" "On"
> 
```

I  disabled the message in https://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr_1.7.5.tar.gz.

Also, I have seen when you extract the HCD energy. Please do not forget to cast the characters to a numeric value. 

Finally, you can add yourself as `ctb` to the package author list in the DESCRIPTION file.

C

**Comment by RogerGinBer** [comment]
Hi @cpanse, while running tests I found that `readTrailer` skips over lines with empty values, so in the case of the field `collisionEnergy` (only defined for >=MS2 scans), the vector is shorter and a mismatch happens respect to other fields: would it be possible to set `blank.lines.skip = FALSE` or consider `readLines` instead of `scan`? 

Here's the `tfstdout` file generated from `readTrailer`, which shows that the empty values are being exported indeed, but they're skipped by `scan`:
[tfstdout.txt](https://github.com/fgcz/MsBackendRawFileReader/files/10925494/example.txt)
image

Other than that, I'm almost done 👍 
To comply with the expected variable types defined in `coreSpectraVariables()`, I'll set `collisionEnergy` (which has to be a numeric vector) to the mean of all energies for each scan (if any), while keeping the raw lists of energies in a new variable `collisionEnergyList` (which is a list of numeric vectors). This way we cover all use cases (single or stepped energies) while being compliant
Does this sound good?

Cheers,
Roger

**Comment by cpanse** [comment]
Good morning @RogerGinBer

I added the scan option and a test case for `readTrailer`.

https://fgcz-ms.uzh.ch/~cpanse/rawrr/rawrr_1.7.6.tar.gz

C

**Pull request merged**
